import 'package:flutter/material.dart';

import './model/category.dart';
import './model/subject.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'SEM-1',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'SEM-2',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'SEM-3',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'SEM-4',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'SEM-5',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'SEM-6',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'SEM-7',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'SEM-8',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'SEM-9',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'SEM-10',
    color: Colors.teal,
  ),
];

const DUMMY_SubjectS = const [
  Subject(
    id: 'm1',
    categories: [
      'c1',
    ],
    title: 'ENGLISH FOR COMMUNICATION',
    affordability: Affordability.Pricey,
    complexity: Complexity.Easy,
    imageUrl:
        'https://lh3.googleusercontent.com/proxy/ebJ1oSK7bZpoy6dFYkCi2EFH3hlOMDVSrOK-AjTN47t5uHW7uQCQgB2-hIpR_TvFlKuoGgFx22hDK0Mkx_e54KQfWDIUEn9ypbBvSJy8sfcUCE4clBAk_gS-O1Loy0jPzPmoWEpcGA',
    resourceUrl: 'https://www.google.com/',
    duration: 4,
    grades: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'The aim of this foundational course is to help the second language learners acquire fluency in both spoken and written English to communicate messages with clarity, precision and confidence in the workplace. The course will have three components: Language, Speaking and Writing. The skills required in these areas will be imparted through Lectures and Sessionals. While lectures will introduce learners to the basic concepts in communication, sessionals will provide handson experience. It is hoped that after commanding the skills required in spoken and written English, learners will be able to communicate better.',
      'Section A (lecture topics) Introduction to communication, Language and grammar skills, speaking skills, Writing skills',
      'Section B (Sessionals) Building Vocabulary, Building sentences, Grammar, Pronunciation drills, Phonetics, vowels, Diphthongs, consonants, Stress, Rhythm and intonation, Conversational skills, Meta Language, the writing process, Writing with a thesis, Writing topic sentences, Writing a paragraph, linking paragraph.',
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
    
  ),
  Subject(
    id: 'm2',
    categories: [
      'c1',
      'c2',
    ],
    title: 'MATHEMATICS',
    affordability: Affordability.Pricey,
    complexity: Complexity.Easy,
    imageUrl:
        'https://images.theconversation.com/files/139426/original/image-20160927-14593-1rf92dt.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=496&fit=clip',
    resourceUrl: 'https://www.google.com/',
    duration: 4,
    grades: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Differential Calculus (Functions of one Variable): Rolle s theorem, Cauchy s mean value theorem (Lagrange s mean value theorem as a special case), Taylor s and Maclaurin s theorems with remainders, indeterminate forms, concavity and convexity of a curve, points of inflexion, asymptotes and curvature.',
      'Differential Calculus (Functions of several variables): Limit, continuity and differentiability of functions of several variables, partial derivatives and their geometrical interpretation, differentials, derivatives of composite and implicit functions, derivatives of higher order and their commutativity, Euler s theorem on homogeneous functions, harmonic functions, Taylor s expansion of functions of several variables, maxima and minima of functions of several variables - Lagrange s method of multipliers. ',
      'Ordinary Differential Equations: First order differential equations - exact, linear and Bernoulli s form, second order differential equations with constant coefficients, method of variation of parameters, general linear differential equations with constant coefficients, Euler s equations, system of differential equations.',
      'Sequences and Series : Sequences and their limits, convergence of series, comparison test, Ratio test, Root test, Absolute and conditional convergence, alternating series, Power series.',
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm3',
    categories: [
      'c1',
      'c2',
    ],
    title: 'BASIC DESIGN',
    affordability: Affordability.Pricey,
    complexity: Complexity.Easy,
    imageUrl:
        'https://mir-s3-cdn-cf.behance.net/project_modules/disp/a2bfdd42770941.56072c22af2f6.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 6,
    grades: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: true,
  ),
  Subject(
    id: 'm4',
    categories: [
      'c1',
    ],
    title: 'INTRO TO ARCHITECTURE',
    affordability: Affordability.Affordable,
    complexity: Complexity.Medium,
    imageUrl:
        'https://i.pinimg.com/originals/37/32/fd/3732fdd05a04d360dbdd179e5413b94b.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    steps: [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm5',
    categories: [
      'c1',
      'c2',
    ],
    title: 'DESCRIPTIVE GEOMETRY',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/0/08/Descriptive_geometry_%281909%29_%2814782090572%29.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm6',
    categories: [
      'c1',
    ],
    title: 'GRAPHICS AND VISUAL COMMUNICATION',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://i.pinimg.com/originals/93/06/e0/9306e02551a717e4af49917c9febd7a2.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 4,
    grades: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm7',
    categories: [
      'c1',
    ],
    title: 'INTRODUCTION TO MANUFACTURING PROCESSES',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Easy,
    imageUrl:
        'https://lh3.googleusercontent.com/proxy/TS2ALfifGZmr8dyvy01fVpECrq1y4Q8Rtd6rmbYdCGFzFMEe-I4hizQxLCtHKS0AZ27YKphkBjIYINKo3Z4QGMZi6qdbhFZ79u1a6vwjKMmsFHaADT1Od71vVFQ9AJLbwPE1lzduHzUr',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm8',
    categories: [
      'c2',
    ],
    title: 'BUILDING MATERIALS',
    affordability: Affordability.Affordable,
    complexity: Complexity.Medium,
    imageUrl:
        'https://structuralengineeringbasics.com/wp-content/uploads/2019/03/STRUCTURAL-ENGINEERING-MATERIALS-1024x530.png',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    isEx: true,
    isA: false,
    isP: false,
    isF: true,
  ),
  Subject(
    id: 'm9',
    categories: [
      'c2',
    ],
    title: 'PROGRAMMING AND DATA STRUCTURES',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://lh3.googleusercontent.com/proxy/v8ebqM35bwdl1mneyZne6JvktPpmp9fwRmHNOvN34KOaK0uI7Qd_lVRTCcS8s1O0iHZHAvP1AjyAZwfoDY-UZ75nzJMIt45qz-Y1',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm10',
    categories: [
      'c2',
    ],
    title: 'PROGRAMMING AND DATA STRUCTURES LAB',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fspecials-images.forbesimg.com%2Fdam%2Fimageserve%2F1106530967%2F960x0.jpg%3Ffit%3Dscale',
    resourceUrl: 'https://www.google.com/',
    duration: 4,
    grades: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm11',
    categories: [
      'c2',
    ],
    title: 'MECHANICS',
    affordability: Affordability.Pricey,
    complexity: Complexity.Easy,
    imageUrl:
        'https://software.intel.com/sites/default/files/managed/4f/3f/deep-learning-inverse-kinematics-figure-3.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 4,
    grades: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Force systems : Moment of a force about a point and about an axis; couple moment; reduction of a force system to a force and a couple.',
      'Equilibrium : Free body diagram; equations of equilibrium; problems in two and three dimensions; plane frames and trusses.',
      'Friction : Laws of Coulomb friction., problems involving large and small contact surfaces; square threaded screws; belt friction; rolling resistance.',
      'Kinematics and Kinetics of particles : Particle dynamics in rectangular coordinates cylindrical coordinates and in terms of path variables; central force motion.',
      'Properties of areas : Moments of inertia and product of inertia of areas, polar moment of inertia, principal axes and principal moments of inertia. ',
      'Torsion : Torsion of cylindrical bars, torsional stress, modulus of rigidity and deformation.',
      'Transformation of stress and strain : Transformation of stress and strain, principal stresses, principal strains, Mohr’s circle for stress and strain.'
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm12',
    categories: [
      'c3',
    ],
    title: 'CLIMATOLOGY AND SOLAR ARCHITECTURE',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://i.ytimg.com/vi/FYheqR5R3QI/maxresdefault.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Climatology and its relation to environmental design, climatic elements – sun, solar radiation, sun-path, temperature, wind, humidity and comfort conditions. Heat flow through design elements, microclimatology, environmental control systems in tropical climates. Design of windows, openings and shading devices. Concepts of solar energy utilization in cooling, heating and lighting the buildings by passive and active methods, photovoltaic cell etc. . Application of solar energy in solar water heating, swimming pool heating, wood seasoning – use of flat plate collectors. Design integration and consolidation for application of solar energy in buildings. ',
    ],
    isEx: false,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm13',
    categories: [
      'c3',
    ],
    title: 'ADVANCED BUILDING MATERIALS AND COMPOSITES',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://structuralengineeringbasics.com/wp-content/uploads/2019/03/STRUCTURAL-ENGINEERING-MATERIALS-1024x530.png',
    resourceUrl: 'https://drive.google.com/drive/u/0/folders/15pBk-DzoK_Sxf6Lm9vfItSklNBaTdYc6',
    duration: 3,
    grades: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Metal and metal components – Basic Metallurgy of Iron & Steel, composite & grades of steel, heat treatment of steel, corrosion of metals and protection, non-ferrous metals-aluminium and aluminium alloys, copper, brass, bronze, lead, zinc, tin ',
      'Precast concrete blocks- their methods of preparation and uses. Paints and varnishes- different types, uses, methods of application on different surfaces',
      'Glass and glazing. Heat insulating and acoustic materials and components. Organic binders and bitumen-&-tar-based materials – Bitumen, tars, emulsions, mastics, waterproofing items, steam-proofing and sealing materials. Polymers and polymer-based materials and components- polymers and plastics, polymer based building materials for walls, pipes, sanitary-ware, glues, mastics. commercial names of common products of respective companies.',
           ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm14',
    categories: [
      'c3',
      'c4',
      'c5',
      'c6',
      'c7',
      'c9',
    ],
    title: 'ARCHITECTURAL DESIGN AND FIELD STUDY',
    affordability: Affordability.Pricey,
    complexity: Complexity.Easy,
    imageUrl:
        'https://media.architecturaldigest.com/photos/55e764da302ba71f30164b4f/master/w_400%2Cc_limit/dam-images-architecture-2014-10-gehry-architecture-best-frank-gehry-architecture-15-walt-disney-concert-hall.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 6,
    grades: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Design theory and application. Application of climatic data, social and structural considerations in more complex design problems such as community centre, studentsâ dormitory, secondary school etc. Analysis of a given design (landmarks in architecture and buildings in India), Design emphasizing forms. Field study tour for historical and modern buildings.',
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: true,
  ),
  Subject(
    id: 'm15',
    categories: [
      'c3',
    ],
    title: 'ENVIRONMENTAL STUDIES',
    affordability: Affordability.Affordable,
    complexity: Complexity.Medium,
    imageUrl:
        'https://www.tutorialspoint.com/environmental_studies/images/environment.jpg',
    resourceUrl: 'https://drive.google.com/drive/u/0/folders/12wIQXn8c85DJSVCHIF1Fzzk6n3dsB8So',
    duration: 3,
    grades: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    steps: [
      'Fundamentals of Ecosystem, Our Earth’s Environment, Human Impact on Environment, Resource and Environment, Environmental pollution, Management of Environment, Environmental legislation, Environmental Quality and Indicators, Environmental Planning and Design Guidelines.',
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm16',
    categories: [
      'c3',
      'c4',
    ],
    title: 'BUILDING CONSTRUCTION',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://www.graymont.com/sites/default/files/inline-images/building-construction.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Brick and Stone masonry: types of brick and their dimensions, bonds in brickwork, classification of stone masonry.',
      'Composite masonry: cement concrete (hollow and solid); hollow clay tile masonry; glass block masonry. Construction details of brick and stone arches including lintels',
      'Timber work: simple carpentry joineries, different types of doors and windows, fixing details of frame, style, rail, panel, glazing including fixtures and fastenings',
      'Different type of staircases including details. Typical section through a load bearing wall showing foundation, plinth, window or door sill, lintel with chajja, roof slab, cornice and parapet details etc.',
      'Roof Trusses: Timber and steel trusses, types; fixing details showing purlin, rafter, tie, strut, cleat etc.',
      'types of roof coverings: tiles, asbestos and metal sheets etc. with fixing details.',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm17',
    categories: [
      'c3',
    ],
    title: 'PHOTOGRAPHY, ART AND ADVANCED VISUAL COMMUNICATION',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://www.asc.upenn.edu/sites/default/files/styles/landing_page_intro_687x375px/public/iStockvisualcommunication.jpg?itok=Z8kwROgR',
    resourceUrl: 'https://drive.google.com/drive/u/0/folders/18mHTZTRGeLlyV70ARt2x7PIG8Cp1wnlY',
    duration: 3,
    grades: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Advanced exercises for fine arts – pencil and charcoal sketching, mixed media rendering, water colour compositions and primary use of acrylic/oil colours; alternative media work such as glass painting, earthen pot painting; Advanced aspects of visual cognition, psychological responses of humans; Art, design, architecture and cinema appreciation; Image doctoring and manipulation using computer software for graphics and animation (Photoshop and Flash). ',
      'Study of the fundamentals of still photography and the camera – Lens types, Aperture and exposure, shutter speed, depth of field, focus, light conditions, light compensation; Comparative assessment of traditional SLR and digital photography. Basic movie camera shooting, traditional analog and digital methods, conversion of analog to digital, memory manipulation and software compatibility exercises; Elementary film editing – video and audio clips, merging, morphing, transitions (with Adobe Premiere).',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm18',
    categories: [
      'c3',
    ],
    title: 'ECONOMICS',
    affordability: Affordability.Pricey,
    complexity: Complexity.Easy,
    imageUrl:
        'https://www.american.edu/cas/economics/images/ma-intl-econ-header-mobile-1709.jpg',
    resourceUrl: 'https://drive.google.com/drive/u/0/folders/1HX0HfGtN-NUjxMQitjldJTgpNeir4wDJ',
    duration: 4,
    grades: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm19',
    categories: [
      'c3',
      'c4',
    ],
    title: 'HISTORY OF ARCHITECTURE',
    affordability: Affordability.Affordable,
    complexity: Complexity.Medium,
    imageUrl:
        'https://www.bergdesignarchitects.com/wp-content/uploads/2017/09/Ancient-Architecture-ancient-history-9232080-1280-800.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    isEx: true,
    isA: false,
    isP: false,
    isF: true,
  ),
  Subject(
    id: 'm20',
    categories: [
      'c4',
    ],
    title: 'WATER SUPPLY AND SANITATION',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://lh3.googleusercontent.com/proxy/kRQeaZ74nFX56IIhSsmefqpPyu6dMN8xWREMHJ0v-UAwjo-HjZi_2hCxgr0lRZgmu_wowhz-mf853ep2LBGl0FQNRjchVEkq-0zpZzo66iu5kLTbWeFwrEU_G3lsCy2DEk0j_De6jbUoA4rwPfciUg',
    resourceUrl: 'https://drive.google.com/drive/u/0/folders/15YJDazz8LFea6BVDdd1v2-W6LfI70Nuk',
    duration: 3,
    grades: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
     'Elements of public water supply system: ',
     'Sources of water, water quality Biochemical Oxygen Demand, intakes, pumping and transportation of water',
     'Conventional water treatment â sedimentation, coagulation, filtration and disinfection. Distribution system, ferrule, water meters, stopcocks, bib cocks, and pipe appurtenances',
     'Building service connections: ',
     'cold and hot water distribution systems in buildings and their design, materials, joints, fittings and valves',
     'Direct and indirect systems, special installation in multistoried buildings',
     'Types of fixtures and materials- wash basins, water closets, urinals, bidets, sinks etc. Over-head and under-ground reservoirs',
     'Conditions of flow in building drainage pipes, traps, vents and their material specifications',
     'Design of drainage and vent pipes, system for low-rise and high-rise buildings, storm water drainage, design of storm drains, building drains, sewers, gully traps, inspection chambers, manholes, connection to public sewer',
     'Waste-water disposal systems, septic tank, soak pits and anaerobic filters, on-site processing and disposal methods',
     'Design of sewerage systems, conventional waste-water treatment, activated sludge, trickling filters etc. Solid wastes collection and removal from buildings',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm21',
    categories: [
      'c4',
    ],
    title: 'STRUCTURAL ANALYSIS',
    affordability: Affordability.Pricey,
    complexity: Complexity.Easy,
    imageUrl:
        'https://image.slidesharecdn.com/cvle212note1-150309133058-conversion-gate01/95/elementary-structural-analysis-notes-1-1-638.jpg?cb=1425907957',
    resourceUrl: 'https://drive.google.com/drive/u/0/folders/1CqxWMtUZ0tuIYV5FMI7odwvSSniNjJHu',
    duration: 4,
    grades: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Energy Method (Ritz) and Error Orthogonalization (Galerkin) for indeterminate beams, curved beams, arches and rings',
      'Matrix Force and Displacement Method for Frames and Trusses- Analysis for temperature stress, lack of fit and settlement of supports; Plastic analysis',
      'Variational Approach – Introduction to Finite element Method for frames, trusses and plane stress analysis',
      'Geometric Stiffness Matrix',
      'Compound Structures, Suspension and guyed Bridges, Influence lines',
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm22',
    categories: [
      'c4',
    ],
    title: 'SURVEYING PRACTICE',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Easy,
    imageUrl:
        'https://guardian.ng/wp-content/uploads/2017/06/survey.jpg',
    resourceUrl: '#',
    duration: 3,
    grades: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Theory: Introduction, Types of Surveys, Chaining, Taping, Corrections, Angle and Direction Measurements, Prismatic compass, Measurement of bearing, Computations of angles from bearings, Theodolite Surveying, Temporary Adjustments, Traversing, Principle of Levelling, Simple and Differential Levelling, Adjustments, Plane table Surveying, Different Methods, Two and Three Point Problems, Minor Surveying Instruments, Setting out Simple Works.',
      'Practicals: Chaining, Offsets, Field book entry, Triangulation & Traversing, Compass Surveying & Traversing, Plane Table Surveying , TwoPoint and Three Point Problems, Levelling, Level book entry, Preparation of contour Map, Study of Theodolites and Angle Measurements, Theodolite Traversing, Techeometric Traversing, Use of Distomat / Theomat, Interpretation of Aerial Photographs & Satellite Imagery. Surveying through Total Station equipment.',     
      ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm23',
    categories: [
      'c4',
    ],
    title: 'COMPUTER AIDED DESIGN AND SIMULATION',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://lh3.googleusercontent.com/proxy/5_yryA-aaFEp_paGsCKHy80QQ9_xDQ7ElERCqPmaxycZZQflViARq5iIIWH45DBHP7GHJyFexDe9-xxzu2el_1A0YCsCJMUNEO0qjYemHfrqo5A3',
    resourceUrl: 'https://drive.google.com/drive/u/0/folders/1TzV0zFBhZwHWQT-KUJwNMGxH0klJS6dt',
    duration: 3,
    grades: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Development of computer programs for three dimensional representation of simple architectural objects (C, C++); AutoCAD application in two and three dimensional architectural drawing, UCS generations, creation of entities, dimensioning. Application of solids and surfaces; Customization of AutoCAD.',
      'Programming in AutoLisp and creation of architectural library elements.',
      'Development of computer programs for design and analysis of building elements, building environments and site developments (C, C++, AutoLisp)',
      'Application of 3D Studio and other 3D-Imaging softwares',
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm24',
    categories: [
      'c4',
    ],
    title: 'ENERGY EFFICIENT DESIGN',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://i.pinimg.com/originals/6e/0c/e5/6e0ce53961680da910afd0015cd74110.jpg',
    resourceUrl: 'https://drive.google.com/drive/u/0/folders/1H0wJoU_AkD1qUJYTNc83x-pN6IyDCs7r',
    duration: 3,
    grades: [
      '9 Ex',
      '13 A',
      '5 B',
      '3 C',
      '1 D',
      '0 F',
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm25',
    categories: [
      'c5',
    ],
    title: 'DEVELOPMENT OF CONTEMPORARY ARCHITECTURE',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://ciptabaliarchitect.com/wp-content/uploads/2019/07/Contemporary-Architecture-1.jpg',
    resourceUrl: 'https://drive.google.com/drive/folders/15JVsD_FUB49wGbG73FinoTZy7wgxMe88',
    duration: 3,
    grades: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Industrial revolution, inventions of building materials and techniques, its influence on prevailing architectural styles in the Continent â Great Exhibitions and achievements in technology and expression.',
      'Search for new forms rationalism, engineering tradition - reinforced and ferro concrete, Arts and Craft Ideals and Art Nouveau movement',
      'American development , Chicago School , Louis Sullivan , architectural system of Frank Lloyd Wright- Grammer of Prairie houses. Responses to mechanisation â Deutscher Werkbund and Futurism, De Stijl and Amsterdam School',
      'New space conceptions , Cubism, Le Corbusierâs quest for ideal form, Bauhaus movement and International style, Walter Gropius, Mies Van de Rohe, Philip Johnson etc. Problem of Regional Identity - movements in Scandinavia and Japan',
      'Detailed discussion on Indian architectsâ works - emphasis on Modernity and Tradition in the regional context',
      'Deconstructionist and architecture in the age of electronic media, emerging concepts. Asa futuristic vision, concluding part of the course gives an idea about present revolution in science and technology, emerging concepts of human habitat, possible changes and future possibilities in architecture ',
      'Some ongoing experiments by leading architects of today are highlighted as path finder. '
    ],
    isEx: false,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm26',
    categories: [
      'c5',
    ],
    title: 'ARCHITECTURAL DETAILING',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://i1.wp.com/www.firstinarchitecture.co.uk/wp-content/uploads/2018/08/The-Full-Package.jpg?w=1080&ssl=1',
    resourceUrl: '#',
    duration: 3,
    grades: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Architectural detailing for common items like: brick and concrete parapet; coping; cornices; string course; chajja; plinth course; plinth protection/ plinth protection with surface drain; treatment of sloped roof with tiles or plaster; paving; steps etc.',
      'Different types of Wall Facing: stone, glazed tiles, earthen tiles and plastic tiles etc. Partition with timber, metal, stone, PVC / plastic etc. Glass curtain walling. R.C.C. and Wooden Staircase including details.',
      'Different types of railing details for staircase, balcony and at roof with brick, timber, metal and plastic etc.Acoustic and thermoinsulating wall paneling with different materials',
      'Suspended ceiling with different materials and finishing including fixing details of lighting fixtures and diffusers for ventilation and air conditioning',
      'Typical detail of rain water pipe connection',
      'Special doors and windows: Sliding, folding, revolving, swinging and rolling etc. with hardware details.Different types of resilient and vibration resistive floors. Layout and details related to Water Supply, Drainage and Sanitation: a case study of a small residential building.',
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm27',
    categories: [
      'c5',
    ],
    title: 'ILLUMINATION AND ELECTRICAL SERVICES',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://southeastelectrical.com.au/wp-content/uploads/2016/05/LED-bulbs-goldcoast-electrical-2-1024x683.jpeg',
    resourceUrl: 'https://drive.google.com/drive/folders/13NwQl5Dvcb_oNLixf-R7VkEnL4jjlDw7',
    duration: 3,
    grades: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Part I – Basics of Electrical Engineering',
      'Introduction: Sources of energy; General structure of electrical power systems. ',
      'DC Networks: Kirchoff’s laws, node voltage and mesh current methods',
      'Single phase AC Circuits: Single phase EMF generation, average and effective values of sinusoids, solution of R,L,C series circuits, the j operator, complex representation of impedances, phasor diagram, power factor, power in complex notation, solution of parallel and series – parallel circuits. ',
      'Three phase AC Circuits: Three phase EMF generation, delta and Y – connections, line and phase quantities, solution of three phase circuits, balanced supply voltage and balanced load, phasor diagram, '
      'Transformers: Construction, EMF equation, ratings, phasor diagram on no load and full load, equivalent circuit, regulation and efficiency calculations, open and short circuit tests, autotransformers.', 
      'Grounding, Earthing and Lightning Protection',
      'Part II – Illumination Engineering',
      'Radiation and colour. • Eye and vision. •',
      'Laws of illumination; illumination from point, line and surface sources. • Photometry and spectrophotometry, photocells.',
      'Different entities of illuminating systems. • Light sources: daylight, incandescent, electric discharge, fluorescent, arc lamps, Lasers and LEDS. •',
      'Environment and glare',
      'Luminaries, wiring, switching and control circuits. ',
      'General illumination design.',
      '• Interior lighting – industrial, residential, office departmental stores, indoor stadium, theater and hospitals.',
      '• Exterior lighting – flood, street, aviation and transport lighting, lighting for displays and signaling – neon sign’s, LED – LCD displays beacons and lighting for surveillance.',
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: true,
  ),
  Subject(
    id: 'm28',
    categories: [
      'c5',
    ],
    title: 'DESIGN OF RC STRUCTURES',
    affordability: Affordability.Pricey,
    complexity: Complexity.Medium,
    imageUrl:
        'https://www.aboutcivil.org/sites/default/files/2017-10/Reinforced-Cement-Concrete-Design.jpg',
    resourceUrl: 'https://drive.google.com/drive/folders/1LTjPwQdKpnny6AP-WEGieOW3TO6_qU5z',
    duration: 4,
    grades: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    steps: [
      'Introduction to the design of Concrete structures',
      'Limit state Analysis',
      'Design of beams for flexure, bond, shear and torsion',
      'Axially and eccentrically loaded Columns',
      'One and two-way Slabs, Flat Slabs, Ribbed slabs',
      'Footings, isolated and combined',
      'Foundations, Raft and pile, Stair cases, Water Tanks and Retaining Walls'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm29',
    categories: [
      'c5',
    ],
    title: 'SPECIFICATIONS',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://structuralengineeringbasics.com/wp-content/uploads/2019/03/STRUCTURAL-ENGINEERING-MATERIALS-1024x530.png',
    resourceUrl: 'https://drive.google.com/drive/folders/1XF_OtU1Rt2rOHfyTPhNBHDYY5ETXMEyl',
    duration: 3,
    grades: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Definition, importance and use of specification: principles and practices, drawing of specification clauses',
      'Specification of common building materials including carriage and stacking of materials',
      'Specification of simple construction. Specifications of BIS and other Institutions.',
      'Prepare the salad',
      'General abbreviations used in specifications and Specification of new building materials.'
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm30',
    categories: [
      'c5',
    ],
    title: 'SOCIOLOGY OF ARCHITECTURE',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://cloudfront.ualberta.ca/-/media/arts/departments-institutes-and-centres/sociology/carousel/goingtowork-lslowry.png',
    resourceUrl: 'https://drive.google.com/drive/folders/1Nl8AMNAoKKiVi0yb42Ae8FUQrupXEyoG',
    duration: 3,
    grades: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Defining Sociology of Architecture as a sub-field of Sociology, the element of society (inequalities, institutions, society and change), theoretical perspectives and methodologies relevant to sociology of Architecture',
      'Built Spaces and socio-cultural reality, built spaces and marginal groups, built spaces and power, gender and built spaces, spaces in continuity and change.',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm31',
    categories: [
      'c5',
    ],
    title: 'CONCRETE LABORATORY',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Easy,
    imageUrl:
        'https://witsolapur.org/images/civillab5.jpg',
    resourceUrl: 'https://drive.google.com/drive/folders/15Bq3iqfTVMs5rbiGwsAVSwWoJF_NUnst',
    duration: 3,
    grades: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'Casting and load-deformation test of reinforced concrete and positioned beams',
      'Cement test: Standard consistency; setting times; compressive strength; fineness and soundness',
      'Aggregate Tests: Sieve analysis; Bulking of sand; Aggregate crushing value; Absorption; Unit weights',
      'HT bars: Yield/ Proof stress, Ultimate Strength, Young s modulus, percentage elongation',
      'Compressive strength of bricks and Pre-conditioning. Load deformation testing of steel beam. Concrete mix design and slump test; Demonstration of flow table, compacting factor and V.B. tests. Study and fixing of electrical resistance strain gages. Determination of E value, Poisson s ratio, Stress Intensity Factor',
      'Calibration of load cells. Dynamics of SDOF, MDOF systems. Photo-elasticity, Properties of hardened concrete and FRC specimens',
      'Compressive strength of cubes by Non-Destructive Testing, Indirect tensile strength of cylinders and FRC cylinders, Modulus of rupture of prisms (2-point and central loading) and FRC prisms',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm32',
    categories: [
      'c6',
    ],
    title: 'STRUCTURAL DETAILING',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Medium,
    imageUrl:
        'https://dl1.cbsistatic.com/i/2017/11/14/3da62493-a34d-4622-a2b2-19e2b4ca1f71/79000494914a20c56a8d03a167c492c9/foreman130936898662automatically-shop-drawings-large-1152x814.jpg',
    resourceUrl: 'https://drive.google.com/drive/folders/1BJhOvmWl5XbdZwbk7UyFsUekj2_-J3Xs',
    duration: 3,
    grades: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Detailing of RC and Steel Structural elements: Reinforced Concrete â Slab, Beams, columns, footing, flat slab, Under ground and overhead water tank; Steel â Detailing of trusses and gusseted joints, Eccentric connections â riveted and welded, beam end connections, built-up column',
    ],
    isEx: true,
    isA: false,
    isP: false,
    isF: true,
  ),
  Subject(
    id: 'm33',
    categories: [
      'c6',
    ],
    title: 'INTERIOR DESIGN',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://d4qwptktddc5f.cloudfront.net/easy_thumbnails/thumbs_WorkshopAPD-CentralParkDuplex.jpg.770x0_q95_crop-smart_upscale.jpg',
    resourceUrl: '#',
    duration: 4,
    grades: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Elements of Interior Design. Transformation of design elements. Optical illusion. Study of geometric patterns. Enveloping space, contained space and residual spaces â spaces within space.Principles of lines â wall composition guidelines. Colour for interiors â hue, chroma and tonal values, Effect of light on colour, various colour schemes like analogues, complementary, triadic etc. Colour symbolism. Industrial colour codes. International standards. Colour planning process.Interior lighting â direct and indirect lighting, location and light grid systems, luminaire types, quality of lighting. Ambient, task and accent lighting. Various systems of Air Conditioning Window, Split and Central.Furniture design. Modular approach in system furnishings. Selection and design of accessories.Principles of interior landscaping â texture, height grouping and layout. Plant species â specifications. Open office system, Industrial interiors and specialized interior space design.Styles of Interiors â Italian, English, French, Japanese styles etc. Exposure to eminent interior designersâ works.Presentation of interior design schemes with detail specification for the materials and technology used. Performance evaluation criteria for the design provisions.',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm34',
    categories: [
      'c6',
    ],
    title: 'HOUSING AND COMMUNITY PLANNING',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://i.ytimg.com/vi/7FLtTHoBgmk/maxresdefault.jpg',
    resourceUrl: 'https://drive.google.com/drive/folders/1liMCSRDsrGz2R8BBUwr8C7Kh_nNjhzdR',
    duration: 3,
    grades: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Housing situation: Impact of industrialization and urbanization, slums and squatter settlements, case studies from India and abroad. Housing for poor people, sites and services, self-help housing, integrated slum improvemen and slum networking',
      'Housing for new communities: norms and standards for dwelling, shopping, education, health and recreational facilities',
      'Neighbourhood concept: densities and their optimization',
      'Cost reduction in housing: techniques and related issues, alternative building materials',
      'Residential environment: users satisfaction and behavioral aspects, evaluation of housing developments',
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm35',
    categories: [
      'c6',
    ],
    title: 'WORKING DRAWING',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://www.bluentcad.com/images/details-in-working-drawings-1280x720.png',
    resourceUrl: 'https://drive.google.com/drive/folders/19nOn7V1acyP6yMqP9mxJwdHOuyhnhCL3',
    duration: 4,
    grades: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Building Construction Drawings to be prepared as a part of the contract documents with proper labeling, dimensioning techniques and brief sceification',
      'The drawings shall be based on building design prepared as design studio assignment',
      'Drawings shall include:Plans: Foundation plan; Ground Floor Plan; Upper Floor Plans; Terrace or Roof plan including roof drainage',
      'Site Plan / layout plan showing different buildings, internal roads, water supply, sewerage including area drainage plan.',
      'Elevations: Elevations of all sides (front, back and both the sides)',
      'Sections: Transverse and Longitudinal sections. Sections through Staircase, Lift, Sanitary units and other full/part details as required.',
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm36',
    categories: [
      'c6',
    ],
    title: 'ESTIMATION AND COSTING',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://lh3.googleusercontent.com/proxy/x9j4XUAK4hv2aHr0rHfLhxdVFH3N-IdlRlL5zdYIvdOzLazl_gWDKAajCOcIU6Rt-_12m62rXG__kvky1fM8EwKXEDgJSWVKruy1-v5cr4oLYtkdoQ',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    isEx: false,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm37',
    categories: [
      'c6',
    ],
    title: 'DESIGN OF STEEL STRUCTURESS',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://readcivil.com/wp-content/uploads/2018/11/structural-glass-ceiling_1112-1176-300x200.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm38',
    categories: [
      'c7',
    ],
    title: 'MATERIAL TESTING LAB',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://www.labtesting.com/wp-content/uploads/2014/12/tensile_testing-250x141.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 4,
    grades: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    isEx: false,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm38',
    categories: [
      'c7',
    ],
    title: 'LANDSCAPE DESIGN AND SITE PLANNING',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://images.squarespace-cdn.com/content/v1/59fb1768268b963c0e1de7a0/1511468527786-ISA3VBMQ8OKJJQNUEL8W/ke17ZwdGBToddI8pDm48kJ5EiY6EOwlfyLe9Ac_bWWV7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0hveExjbswnAj1UrRPScjfBkb_9ZVp0lG4K38uFIbUlqieBMejQT4y9tBKifYyTpzw/IMG_20160710_211658.jpg?format=1000w',
    resourceUrl: 'https://www.google.com/',
    duration:3,
    grades: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm39',
    categories: [
      'c7',
    ],
    title: 'AIR CONDITIONING',
    affordability: Affordability.Pricey,
    complexity: Complexity.Easy,
    imageUrl:
        'https://www.bowersoxair.com/wp-content/uploads/2019/06/airconditionertrends-1-1080x675.jpeg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    steps: [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: true,
  ),
  Subject(
    id: 'm40',
    categories: [
      'c7',
    ],
    title: 'BUILDING ACOUSTICS',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Medium,
    imageUrl:
        'https://host03.t1.net.au/~raywalsh/wp-content/uploads/2017/07/Room-Acoustics-300x131.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    steps: [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm41',
    categories: [
      'c8',
    ],
    title: 'OFFICE TRAINING',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Easy,
    imageUrl:
        'https://i.ya-webdesign.com/images/training-clipart-office-training-5.png',
    resourceUrl: 'https://www.google.com/',
    duration: 0,
    grades: [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    steps: [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm42',
    categories: [
      'c8',
    ],
    title: 'FIELD OBSERVATION',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://uxstudioteam.com/website/wp-content/uploads/2017/07/Field-Research-Not-a-Case-Study--720x480.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 0,
    grades: [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    steps: [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm43',
    categories: [
      'c8',
    ],
    title: 'SITE SUPERVISION',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://akafi.net/storage/sub_imgMiddle/middle_1_ca4c7c0945_%D9%85%D9%82%D8%A7%D9%88%D9%84-%D9%88%D9%85%D9%82%D8%A7%D9%88%D9%84%D8%A7%D8%AA-%D9%85%D8%B4%D8%A7%D8%B1%D9%8A%D8%B9-%D8%B5%D9%86%D8%A7%D8%B9%D8%A9-%D8%AA%D8%AC%D8%A7%D8%B1%D8%A9-%D9%85%D9%82%D8%A7%D9%88%D9%84%D9%8A%D9%86.jpeg',
    resourceUrl: 'https://www.google.com/',
    duration: 0,
    grades: [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    steps: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm44',
    categories: [
      'c8',
    ],
    title: 'CRITICAL APPRAISAL',
    affordability: Affordability.Pricey,
    complexity: Complexity.Medium,
    imageUrl:
        'https://s3.amazonaws.com/libapps/accounts/40836/images/Schermafbeelding_2016-10-06_om_23.40.11.png',
    resourceUrl: 'https://www.google.com/',
    duration: 0,
    grades: [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    steps: [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    isEx: true,
    isA: false,
    isP: false,
    isF: true,
  ),
  Subject(
    id: 'm45',
    categories: [
      'c8',
    ],
    title: 'DOCUMENTATION OF INNOVATIVE DETAILS',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://www.thetimes24.com/wp-content/uploads/2019/10/most-innovative-states-e1571564074951.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 0,
    grades: [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    steps: [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    isEx: true,
    isA: false,
    isP: true,
    isF: false,
  ),
  Subject(
    id: 'm46',
    categories: [
      'c9',
    ],
    title: 'PRINCIPLES OF TOWN PLANNING AND URBAN DESIGN',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Easy,
    imageUrl:
        'https://www.arup.com/-/media/arup/images/expertise/services/townplanningconceptural-planning-for-dongting-new-town-hunan-chinac-arup.jpg?h=1125&w=2000&hash=88826E23D523D51C9423678037397295',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm47',
    categories: [
      'c9',
      'c10',
    ],
    title: 'PROJECT-(THESIS)',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Easy,
    imageUrl:
        'https://archinect.imgix.net/uploads/z1/z1tgvxr7g4x13xzm.jpg?fit=crop&auto=compress%2Cformat&w=615',
    resourceUrl: 'https://www.google.com/',
    duration: 12,
    grades: [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    steps: [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    isEx: true,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm48',
    categories: [
      'c9',
    ],
    title: 'CONSTRUCTION PROJECT MANAGEMENT',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://cdn.technologyadvice.com/wp-content/uploads/2017/08/Fotolia_98303431_Subscription_Monthly_M-699x408.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    steps: [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    isEx: false,
    isA: true,
    isP: true,
    isF: true,
  ),
  Subject(
    id: 'm49',
    categories: [
      'c10',
    ],
    title: 'COMPREHENSIVE VIVA-VOCE',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://easyshiksha.com/institutes_informations/images/20_1.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 0,
    grades: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm50',
    categories: [
      'c10',
    ],
    title: 'PROFESSIONAL PRACTICE AND BUILDING BYELAWS',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://www.polytechnichub.com/wp-content/uploads/2018/04/building-bye-laws.gif',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
  Subject(
    id: 'm51',
    categories: [
      'c10',
    ],
    title: 'SEMINAR',
    affordability: Affordability.Affordable,
    complexity: Complexity.Easy,
    imageUrl:
        'https://www.jic.ac.uk/app/uploads/2018/11/Friday-Seminars.jpg',
    resourceUrl: 'https://www.google.com/',
    duration: 3,
    grades: [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    steps: [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    isEx: false,
    isA: false,
    isP: false,
    isF: false,
  ),
];
